src/Cosaco/GesenBundle/Entity/Usuario.php
<?php

namespace Cosaco\GesenBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;

/**
 * Usuario
 */
class Usuario implements AdvancedUserInterface, \Serializable
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $cargo;

    /**
     * @var string
     */
    private $nombres;
    
    /**
     * @var string
     */
    private $apellidos;

    /**
     * @var string
     */
    private $user;

    /**
     * @var string
     */
    private $userpw;

    /**
     * @var \DateTime
     */
    private $fechaActualizacion;

    /**
     * @var string
     */
    private $estado;
    
    /**
     * @var string
     */
    private $roles;

    /*
     *  Get string
     * 
     * @return string
     */
    public function __toString() {
        return $this->nombres. ' ' .$this->apellidos;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set cargo
     *
     * @param string $cargo
     * @return Usuario
     */
    public function setCargo($cargo)
    {
        $this->cargo = $cargo;

        return $this;
    }

    /**
     * Get cargo
     *
     * @return string 
     */
    public function getCargo()
    {
        return $this->cargo;
    }

    /**
     * Set nombres
     *
     * @param string $nombres
     * @return Usuario
     */
    public function setNombres($nombres)
    {
        $this->nombres = $nombres;

        return $this;
    }

    /**
     * Get nombres
     *
     * @return string 
     */
    public function getNombres()
    {
        return $this->nombres;
    }
    
    /**
     * Get nombres
     *
     * @return string 
     */
    public function getPrimerNombre()
    {
        // Convertimos en array la cadena separando por espacios
        $nombre=explode(" ", $this->nombres);
        
        // Retornamos el primer nombre
        return $nombre[0];
    }

    /**
     * Set apellidos
     *
     * @param string $apellidos
     * @return Usuario
     */
    public function setApellidos($apellidos)
    {
        $this->apellidos = $apellidos;

        return $this;
    }

    /**
     * Get apellidos
     *
     * @return string 
     */
    public function getApellidos()
    {
        return $this->apellidos;
    }

    /**
     * Set user
     *
     * @param string $user
     * @return Usuario
     */
    public function setUser($user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return string 
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set userpw
     *
     * @param string $userpw
     * @return Usuario
     */
    public function setUserpw($userpw)
    {
        $this->userpw = $userpw;

        return $this;
    }

    /**
     * Get userpw
     *
     * @return string 
     */
    public function getUserpw()
    {
        return $this->userpw;
    }

    /**
     * Set fechaActualizacion
     *
     * @param \DateTime $fechaActualizacion
     * @return Usuario
     */
    public function setFechaActualizacion($fechaActualizacion)
    {
        $this->fechaActualizacion = $fechaActualizacion;

        return $this;
    }

    /**
     * Get fechaActualizacion
     *
     * @return \DateTime 
     */
    public function getFechaActualizacion()
    {
        return $this->fechaActualizacion;
    }

    /**
     * Set estado
     *
     * @param string $estado
     * @return Usuario
     */
    public function setEstado($estado)
    {
        $this->estado = $estado;

        return $this;
    }

    /**
     * Get estado
     *
     * @return string 
     */
    public function getEstado()
    {
        return $this->estado;
    }


    /**
     * Set roles
     *
     * @param string $roles
     * @return Usuario
     */
    public function setRoles($roles)
    {
        $this->roles = $roles;

        return $this;
    }


    
    /*
     *  Metodos para iniciar sesion
     */
    
    /*
     * Usuario
     * 
     * @return string 
     */
    public function getUsername() {
        return $this->user;
    }
    
    /*
     * Password
     *
     * @return string 
     */
    public function getPassword() {
        return $this->userpw;
    }
    
    /**
     * Get roles
     *
     * @return string 
     */
    public function getRoles()
    {
        return array($this->roles);
    }
    
   /**
     * @inheritDoc
     */
    public function eraseCredentials()
    {
    }


    /**
     * @see \Serializable::serialize()
     */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->user,
            $this->userpw,
            // see section on salt below
            // $this->salt,
        ));
    }

    /**
     * @see \Serializable::unserialize()
     */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->user,
            $this->userpw,
            // see section on salt below
            // $this->salt
        ) = unserialize($serialized);
    }

    public function getSalt() {
        
    }

    public function isAccountNonExpired() {
        return true;
    }

    public function isAccountNonLocked() {
        return true;        
    }

    public function isCredentialsNonExpired() {
         return true;       
    }

    public function isEnabled() {
        
        if($this->estado=='a') {
            return true;
            
        } else {
            return false;
        }
    }

}

src/Cosaco/GesenBundle/Resources/views/layout.html.twig
{% extends "::base.html.twig" %}

{% block body %}
<div id="header">
    <nav id="gsn-nav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <!-- Boton que despliega el menu en pantallas pequeñas -->
                <button id="gsn-btn-nav-menu" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gsn-nav-menu">
                    <span class="sr-only">Menú</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><strong>Gesen v1</strong></a>
            </div>
            <!-- Barra contenedora del menu -->
            <div id="gsn-nav-menu" class="collapse navbar-collapse navbar-right">
            <ul id="gsn-nav-menu-links" class="nav navbar-nav">
                <li class="gsn-active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <ul id="gsn-nav-menu-sesion" class="nav navbar-nav">
                <li class="dropdown"{% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}  style="display:none;"{% endif %}>
                    <!-- Formulario login -->  
                    <a href="#" class="gsn-dropdown-login" data-toggle="dropdown" role="button" aria-expanded="false">
                        <span class="glyphicon glyphicon-user"></span><span class="gsn-user-perfil-name"> Login</span>
                    </a>
                    <div id="gsn-nav-menu-form" class="dropdown-menu dropdown-menu-right" role="menu">
                        <!--Panel desplegable contenedor del formulario de login -->{% block login %}{% include 'CosacoGesenBundle:Seguridad:login_form.html.twig' with {'error':'', 'last_username':''} %}{% endblock %}
                    </div>
                </li>
                <li class="dropdown"{% if not is_granted('IS_AUTHENTICATED_REMEMBERED') %}  style="display:none;"{% endif %}>
                    <!-- Menu de usuario -->
                    <a href="#" class="gsn-dropdown-user" data-toggle="dropdown" role="button" aria-expanded="false" data-user_id="{% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}{{ app.user.id }}{% else %}0{% endif %}">
                        <span class="gsn-user-perfil-name">Hola </span><span>{% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}{{ app.user.primerNombre }}{% endif %}</span> <span class="glyphicon glyphicon-chevron-down"></span>                            
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right" role="menu">
                        <!-- Menu desplegable del usuario -->
                        <li><a href="#">Perfil</a></li>
                        <li class="gsn-cerrar-sesion"><a href="{{ path('gsn_logout') }}">Cerrar sesión</a></li>
                    </ul>
                </li>
              </ul>
            </div><!-- /.navbar-collapse --> 
        </div>
    </nav>                       
</div>   
<div id="body">
    <div class="container-fluid"> 
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <div class="gesen-logo">
                    <img src="{{ asset('img/cosaco_md.png') }}" />
                </div>
                <ul class="nav nav-sidebar">
                    <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
                    <li><a href="#">Reports</a></li>
                    <li><a href="#">Analytics</a></li>
                    <li><a href="#">Export</a></li>
                </ul>
                <ul class="nav nav-sidebar">
                    <li><a href="#">Nav item</a></li>
                    <li><a href="#">Nav item again</a></li>
                    <li><a href="#">One more nav</a></li>
                    <li><a href="#">Another nav item</a></li>
                    <li><a href="#">More navigation</a></li>
                </ul>
            </div>        
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">   
        <!-- bloque contenido -->{% block cont_derecha %}
{% endblock %}
        </div> 
    </div>
</div>
        
    {{ dump(app.user) }}
{% endblock %}
    
    